
(async () => {

    try {
        console.log("entrypoint");
    }
    catch{
        console.log("exception!");
    }
})();
